### ISSUE TITLE
Search for a Park

### ISSUE THREAD

**Issue by kalargent** [IAmShawn98/national-park-finder#1]
## Story 

As a user, I want to search for national parks by Zip Code, so that I can see parks near me, or near where I want to go. 

## AC 
 - [x] index.html has a field to take in a state search parameter.
 - [x] index.html has a search button. 
 - [x] Entering and submitting a search returns results populated in a table. 10 parks are retrieved by default. 

## Tasks to Accomplish AC 
Shawn 
 - [x] FE - Use bootstrap to create a form text field to accept search terms
 - [x] FE - Table to populate the results - bootstrap 

Patrick/Karen 
 - [x] BE - Construct an initial query URL to get a response from the API - KL
 - [x] BE - Construct a URL that can take in dynamic parameters - KL
 - [x] BE - Use data from search fields to create URL and retrieve parks - KL/SL
 - [x] BE - Use NPS API to return a list of parks meeting the criteria - KL  
 - [x] BE - Write code to populate the API results  into a table on the FE - KL/SL

 
## Items to discuss for implementation
