### ISSUE TITLE
Save a Park as a Favorite

### ISSUE THREAD

**Issue by kalargent** [IAmShawn98/national-park-finder#8]
## Story 
As a user, I want to save one or more parks to a list of favorites, so that I can come back and look at them later. 

## AC 
 - [ ] Users can select one or more parks from the table. 
 - [ ] Users can click a button to add parks to a list of favorites. 
 - [ ] Users can view the list of favorites (perhaps we make a panel on the left under the search fields to display them?).
 - [ ] Users can click on the park in the favorites list and display the park information. 

## Task Breakdown
